name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven

    - name: Setup node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache for maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache for npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('.github/workflows/release.yml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup semantic-release
      run: npm install -g @conveyal/maven-semantic-release@v4.5.0 semantic-release@15 @semantic-release/exec@v3.3.8

    - name: Release
      run: semantic-release --branch master --use-conveyal-workflow --skip-maven-deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
