name: Release

on:
  release:
    types: [created]
  push:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload workflow artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-binaries
        path: /home/runner/work/keycloak-remember-me-authenticator/keycloak-remember-me-authenticator/target/*.jar

  upload:
    name: Upload release binaries
    if: github.event_name == 'release'
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-binaries

    - name: Upload release artifacts
      run: gh release upload "$GITHUB_REF_NAME" /home/runner/work/keycloak-remember-me-authenticator/keycloak-remember-me-authenticator/*.jar
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
